# Generated by Django 4.2.1 on 2024-06-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='День рождения'),
        ),
    ]
