# Generated by Django 4.2.1 on 2024-03-23 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpost',
            name='category',
            field=models.CharField(choices=[('C++', 'C++'), ('C#', 'C#')], default='C++', max_length=50),
        ),
    ]
