# Generated by Django 4.2.1 on 2024-05-31 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpost',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascript', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logo.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='screenshot',
            field=models.ManyToManyField(blank=True, related_name='screenshots', to='logo.screenshots', verbose_name='Скриншоты'),
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='logo.tagpost', verbose_name='Тэги'),
        ),
        migrations.AddField(
            model_name='screenshots',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logo.scriptpost'),
        ),
        migrations.AddIndex(
            model_name='scriptpost',
            index=models.Index(fields=['-time_create'], name='logo_script_time_cr_e42343_idx'),
        ),
    ]
