# Generated by Django 4.2.1 on 2024-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0003_alter_scriptpost_options_scriptpost_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
