# Generated by Django 4.2.1 on 2024-06-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=100, verbose_name='Комментарий'),
        ),
    ]
