# Generated by Django 4.2.1 on 2024-06-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0004_alter_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
