# Generated by Django 4.2.1 on 2024-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0004_alter_scriptpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpost',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Rough post'), (1, 'Published')], default=0),
        ),
    ]
