# Generated by Django 4.2.1 on 2024-03-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0005_alter_scriptpost_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='scriptpost',
            name='category',
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='cat_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='logo.category'),
        ),
    ]
