# Generated by Django 4.2.1 on 2024-06-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0006_scriptpost_likes_count_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpost',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=1, verbose_name='Статус'),
        ),
    ]
