# Generated by Django 4.2.1 on 2024-03-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0010_alter_scriptpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='sp_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
