# Generated by Django 4.2.1 on 2024-04-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0011_author_sp_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascript', to='logo.author'),
        ),
    ]
