# Generated by Django 4.2.1 on 2024-04-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0012_alter_scriptpost_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptpost',
            options={'ordering': ['-time_create'], 'verbose_name': 'Пользовательские публикации', 'verbose_name_plural': 'Пользовательские публикации'},
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
