# Generated by Django 4.2.1 on 2024-04-23 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0013_alter_scriptpost_options_scriptpost_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='about',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ascript', to='logo.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logo.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='content',
            field=models.TextField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='logo.tagpost', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='scriptpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
