# Generated by Django 4.2.1 on 2024-05-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0015_alter_scriptpost_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptpost',
            name='screenshot',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Скриншоты'),
        ),
    ]
