# Generated by Django 4.2.1 on 2024-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0016_scriptpost_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d', verbose_name='Скриншоты')),
            ],
            options={
                'verbose_name': 'Скриншоты',
                'verbose_name_plural': 'Скриншоты',
            },
        ),
        migrations.RemoveField(
            model_name='scriptpost',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='scriptpost',
            name='screenshot',
            field=models.ManyToManyField(to='logo.screenshots'),
        ),
    ]
