# Generated by Django 4.2.1 on 2024-05-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0018_screenshots_post_alter_scriptpost_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptpost',
            name='screenshot',
            field=models.ManyToManyField(blank=True, related_name='screenshots', to='logo.screenshots', verbose_name='Скриншоты'),
        ),
    ]
