# Generated by Django 4.2.1 on 2024-05-07 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logo', '0019_alter_scriptpost_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='logo.scriptpost'),
        ),
    ]
